### ISSUE TITLE
How to Enable/Disable Translation management from PowerShell

### ISSUE THREAD

**Issue by WeiweiCai** [RWS/ISHRemote#166]
We are using ISHRemote to create target layer to system with following code:
`Add-IshDocumentObj -IshFolder $topicfolder -FileContent $tpoicfilecontent -LogicalId $GUID -Metadata $topicmetadata -Lng $language -Version $topicobj.version_version_value -IshType ISHModule -IshSession $ishSession`

But we get below exception when creating topic file target layer:
System.ServiceModel.FaultException`1[Trisoft.ISHRemote.DocumentObj25ServiceReference.InfoShareFault]: [-136] Target languages will be created automat
ically when source language is released. If you want to add more than one translation manually, please disable translation management. [136;AlreadyAnAuthLngForVersion] (F
ault Detail is equal to Trisoft.ISHRemote.DocumentObj25ServiceReference.InfoShareFault).

Once we uncheck "Enable translation management" option from website, above error will go.
Now, we want to disable the Translation management from PowerShell script to make sure we can create topic target layer successful, but we didn't find any command from ISHRemote to do it.
We have tried set metadata with following code and then use Set-IshDocumentObj to update the IshDocumentObj, but it doesn't work.
```
$updateStatus = Set-IshMetadataField -Name “FNOTRANSLATIONMGMT” -Level “Lng” -Value “yes”
Set-IshDocumentObj -LogicalId {GUID} -Lng "{language}" -Version {version} -Metadata $updateStatus
```

How can we set the "Enable translation management" option from PowerShell? Thanks.

**Comment by ddemeyer** [comment]
Sure you can. You are actually pretty close, you are applying the field to the wrong level - it should be `Logical` instead of `Lng` . (And depending on the ISHRemote version you get a warning or server-side error on that).

```powershell
$requestedMetadata = Set-IshRequestedMetadataField -Name FNOTRANSLATIONMGMT -Level Logical -ValueType Element
$o = Get-IshDocumentObj -LogicalId GUID-0B0EDD21-3C75-426F-BADE-8C2FA41E4F8B -RequestedMetadata $requestedMetadata

$metadata = Set-IshMetadataField -Name FNOTRANSLATIONMGMT -Level Logical -ValueType Element -Value FALSE
Set-IshDocumentObj -IshObject $o -Metadata $metadata
```

The field FNOTRANSLATIONMGMT  (an unfortunate name from the 90s :)) is a System field which is not typically retrieved by ISHRemote but as the above sample shows, can be added. Do note that the field controls (Push) Translation Management, so if you disabled Translation Management to manually add your own language stubs/cards/files, then Translation Management will skip this Logical object in the future. You can of course temporarily disable and then after your Add re-enable.

A good tip is that you can check accurate field names and levels through `Get-IshTypeFieldDefinition`. Some description is on https://github.com/RWS/ISHRemote/blob/master/Doc/ReleaseNotes-ISHRemote-0.13.md#type-and-field-setup

**Comment by WeiweiCai** [comment]
@ddemeyer  Thanks for your quick response. 

Based on your code snippet, I didn't get any error any more, sees it is executed as expected. But when we check from website, the "Enable translation management" option still not be updated.
![image](https://github.com/RWS/ISHRemote/assets/15260217/22f069a8-5b4d-4633-8b10-15b47497df82)

**Comment by ddemeyer** [comment]
Hi @WeiweiCai ... Did you try the other way round, as I indicated _FNOTRANSLATIONMGMT (an unfortunate name from the 90s :))_ ... so field "NO Translation Mgmt" set to `FALSE` means 'Translation Management" is enabled. In turn field "NO Translation Mgmt" set to `TRUE` means disabled.

**Comment by WeiweiCai** [comment]
Thanks for your clarify, I can disable it by set the FNOTRANSLATIONMGMT field as TRUE now.
Thanks again for your help. :)
