### ISSUE TITLE
Support for PowerShell Core 6?

### ISSUE THREAD

**Issue by tintinno** [RWS/ISHRemote#81]
Can you add support for PowerShell Core 6? 
PS Core 6 removed support for Snap-ins, so loading ISHRemote returns the error:

> Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=6.2.4.0, ... 

I'm sure this is a non-trivial task, but on the positive side, the file `Source/ISHRemote/Trisoft.ISHRemote/ISHRemoteCmdlets.cs` appears to be the only one that mentions "SnapIn."

**Comment by ddemeyer** [comment]
Hi @tintinno 
There is a bigger problem as mentioned on [ISHRemote > Prerequisites](https://github.com/sdl/ISHRemote#prerequisites) as

> Note that we rely on Windows PowerShell (FullCLR), and not PowerShell Core (CoreCLR) which relies on .NET Core. Main reason is that the Core edition doesn't offer all supporting libraries for WS-Trust based authentication like System.IdentityModel and System.ServiceModel.

So a true PowerShell 6/7 .NET Core based library is not happening soon I'm afraid. Although we are working on it.

**Comment by Sarafian** [comment]
Indeed. The .net team has unofficially declined any further support into WCF and SOAP and have replaced even WCF with gPRC.

As of .net3.0, it is possible to load full. Net Framework assemblies as part the runtime (e.g. wpf apps) and that could been that powershell 7 should be able to achieve something similar with ishremote and its dependencies. This is because Microsoft has recognized that while killing powershell ise for 5, they've not offered a proper replacement for legacy Windows dependencies and they want to without implicit remoting as it is currently possible. If it manages to work it will only with in Windows of coarse.

With .net5 everything is going to unify under one sdk and runtime and good things are expected for powershell as well. But it is unclear still how it will work. But that is good the future.

**Comment by ddemeyer** [comment]
Time moves on, and I'm happy to close this issue with the release of ISHRemote v7, see https://github.com/sdl/ISHRemote/blob/master/Doc/ReleaseNotes-ISHRemote-7.0.md and https://github.com/RWS/ISHRemote/releases/tag/v7.0 for more details.

In short ISHRemote v7 works on PowerShell (Core) v7+ as you know it, except Windows Authentication (mostly known as Microsoft ADFS). It all works as before on Windows PowerShell 5.1.
